services:
  - type: web
    name: agendakarol
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CAL_SECRET
        sync: false
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_DB
        sync: false
      - key: ZAPI_INSTANCE
        sync: false
      - key: ZAPI_TOKEN
        sync: false
      - key: ZAPI_CLIENT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false 